### ISSUE TITLE
Create authorization mechanism for users

### ISSUE THREAD

**Issue by tawfiknasser** [WebAhead-cs2/caps-look-api#7]
Implement middleware that verify user roles to access specific endpoint.

The authorize module shall be generic and can be used all over the system.

use the jwt that is provided in the cookies.

could be helpful resources:

https://www.google.com/search?q=jwt&oq=jwt

https://stackabuse.com/authentication-and-authorization-with-jwts-in-express-js/

**Comment by hanihakim** [comment]
the assignment have been created 17 days ago, but wasn't ready to start working on the task.
at 5.2.23 the merge of the token have been completed.

**Comment by hanihakim** [comment]
the task is finished locally. i tried to push the task i see that i forgot to make a new branch for the task as im still on DEV branch (i get the message :  

remote: Resolving deltas: 100% (6/6), completed with 3 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/dev.
remote: error: At least 3 approving reviews are required by reviewers with write access. Cannot change this locked branch
To https://github.com/WebAhead-cs2/caps-look-api.git
 ! [remote rejected] dev -> dev (protected branch hook declined)
error: failed to push some refs to 'https://github.com/WebAhead-cs2/caps-look-api.git'

i sent a message to tofiq to assist

**Comment by tawfiknasser** [comment]
@hanihakim it says `! [remote rejected] dev -> dev (protected branch hook declined) ` so assume you are working on`dev` branch.
you shall checkout to a new feautre branch. `git checkout -b "your_branch_name"` then from there add, commit and push your work. after you succeed this step. create a new Pull request in the github.
